account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^register/$', views.register, name="register"),
    # url('^register/success/$', views.register_success, name="register_success"),
	url(r'^login/$', views.login, name='login'),
	url(r'^logout/$', views.logout, name='logout'),	
	url(r'^password_reset/$', views.password_reset,  name='password_reset'),
] 

products/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),	
	url(r'^(?P<product_id>[0-9]+)/ingredients/$', views.ingredient_get, name='ingredients'),
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	url(r'^(?P<product_id>[0-9]+)/ingredient_pick/$', views.ingredient_pick, name='ingredient_pick'),	
] 

syonlinestore/urls.py
from django.conf.urls import include, url
from django.contrib import admin

admin.site.site_header = 'SY Online Store Admin'
admin.site.site_title = 'SY Online Store Admin'
urlpatterns = [
	url(r'^products/', include('products.urls', namespace="products")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/',include('account.urls', namespace="account")),
    url(r'^accounts/',include('account.urls', namespace="account")),
]

products/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.
class Product(models.Model):
	pname = models.CharField(max_length=200)
	pdesc = models.CharField(max_length=200,null=True,blank=True)
	pstatus = models.BooleanField(default=True)
	pdate = models.DateTimeField('add date',default=datetime.datetime.now)
	pimage = models.FileField(upload_to='files/%Y/%m/%d/',max_length=100,null=True,blank=True)
	
	def was_published_recently(self):
		now = timezone.now();
		return now >= self.pdate >= timezone.now() - datetime.timedelta(days=1)
	was_published_recently.admin_order_field = 'pdate'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'
	def __str__(self):
		return '%s : %s' % (self.pname,self.pdesc)
 
class Ingredient(models.Model):
	product = models.ForeignKey(Product)
	iname = models.CharField(max_length=200)
	idesc = models.CharField(max_length=200,null=True,blank=True)

	def __str__(self):
		return '%s : %s' % (self.iname,self.idesc)
 

products/forms.py
from django import forms

class NameForm(forms.Form):
	your_name = forms.CharField(label="Your Name", max_length=100)

products/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.http import Http404
from django.template import RequestContext, loader
from django.views import generic
from .models import Product,Ingredient
from django.core.urlresolvers import reverse
# Create your views here.

# def index(request):
# 	latest_product_list = Product.objects.order_by('-pdate')[:5]
# 	context = {'latest_product_list': latest_product_list}
# 	return render(request, 'products/index.html', context)
	# template = loader.get_template('products/index.html')
	# context = RequestContext(request, {
	# 	'latest_product_list': latest_product_list
	# 	})
	# return HttpResponse(template.render(context))

# def detail(request, product_id):
# 	product = get_object_or_404(Product, pk=product_id)
# 	return render(request, 'products/detail.html',{'product': product}) 
	# try:
	# 	product = Product.objects.get(pk=product_id)
	# except Product.DoesNotExist:
	# 	raise Http404("product does not exist")
	# return render(request, 'products/detail.html',{'product': product})

def ingredient_get(request, product_id):
	response = "You're looking at ingredients of product %s."
	return HttpResponse(response % product_id)

def ingredient_pick(request, product_id):
	p = get_object_or_404(Product, pk=product_id)
	try:
		selected_ingredient = p.ingredient_set.get(pk=request.POST['ingredient'])
	except (KeyError, Ingredient.DoesNotExist):
		return render(request, 'products/detail.html',{
			'question' :p,
			'error_message': "You didn't select a ingredient."
			})
	else:
		selected_ingredient.save()
		return HttpResponseRedirect( reverse('products:results',args=(p.id,)))

# def results(request, product_id):
#     product = get_object_or_404(Product, pk=product_id)
#     return render(request, 'products/results.html', {'product': product})

class IndexView(generic.ListView):
    template_name = 'products/index.html'
    context_object_name = 'latest_product_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Product.objects.order_by('-pdate')[:5]


class DetailView(generic.DetailView):
    model = Product
    template_name = 'products/detail.html'


class ResultsView(generic.DetailView):
    model = Product
    template_name = 'products/results.html'

products/templates/products/detail.html
<h1>{{ product.pname }}</h1>
{% if error_message %} <p><strong>{{ error_message }}</strong></p> {% endif %}

<!-- <ul>
{% for ingredient in product.ingredient_set.all %}
    <li>{{ ingredient.iname }}</li>
{% endfor %}
</ul> -->

<form action="{% url 'products:ingredient_pick' product.id %}" method="post">
{% csrf_token %}
{% for ingredient in product.ingredient_set.all %}
    <input type="radio" name="ingredient" id="ingredient{{ forloop.counter }}" value="{{ ingredient.id }}" />
    <label for="ingredient{{ forloop.counter }}">{{ ingredient.iname }}</label><br />
{% endfor %}
<input type="submit" value="Pick" />
</form>

products/templates/products/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'products/style.css' %}" />
{% if latest_product_list %}
    <ul>
    {% for product in latest_product_list %}
        <li><a href="{% url 'products:detail' product.id %}">{{ product.pname }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No products are available.</p>
{% endif %}

products/templates/products/results.html
<h1>{{ product.pname }}</h1>

<ul>
{% for ingredient in product.ingredient_set.all %}
    <li>{{ ingredient.iname }} </li>
{% endfor %}
</ul>

<a href="{% url 'products:detail' product.id %}">Vote again?</a>